# Generated by Django 3.1.7 on 2021-05-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210515_1748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
